---
- name: Hello World!
  hosts: all
 
  tasks:
 
  - name: Hello World!
    shell: echo "Hi! Tower is working."
    
  - name: Write backup script for each app
    shell: echo 'line one' >> test.txt

  - name: Store file into /tmp/fetched/host.example.com/tmp/somefile
    ansible.builtin.fetch:
      src: test.txt
      dest: /home/s/testsaeed.txt
    
#  - name: Copy compressed file
#    ansible.builtin.copy:
#      src: /home/s/pt.tar.gz
#      dest: /home/s/pt.tar.gz

#  - name: Extract file
#    ansible.builtin.unarchive:
#      src: pt.tar.gz
#      dest: /home/s/
#      remote_src: yes
