---
- name: Demo playbook
  hosts: 192.168.100.118
  remote_user: s

  tasks:
  - name: Extract foo.tgz into /var/lib/foo
    ansible.builtin.unarchive:
      src: /home/s/pt.tar.gz
      dest: /home/s/
      
