---
- name: Demo playbook
  hosts: servers
  remote_user: s

  tasks:
  - name: Copy test file
    ansible.builtin.copy:
      src: /home/s/pt.tar.gz
      dest: /home/s/pt.tar.gz

  - name: Extract foo.tgz into /var/lib/foo
    ansible.builtin.unarchive:
      src: /home/s/pt.tar.gz
      dest: /home/s/
      
